# Generated by Django 2.0.2 on 2018-06-11 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_productosdeseados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosdeseados',
            name='id_user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
