# Generated by Django 2.0.2 on 2018-05-28 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20180515_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallefactura',
            name='sub_total',
        ),
    ]
