# Generated by Django 2.0.2 on 2018-05-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('imagen1', models.ImageField(blank=True, height_field='height_field1', null=True, upload_to='', width_field='width_field1')),
                ('height_field1', models.IntegerField(default=0)),
                ('width_field1', models.IntegerField(default=0)),
                ('imagen2', models.ImageField(blank=True, height_field='height_field2', upload_to='', width_field='width_field2')),
                ('height_field2', models.IntegerField(default=0)),
                ('width_field2', models.IntegerField(default=0)),
                ('imagen3', models.ImageField(blank=True, height_field='height_field3', upload_to='', width_field='width_field3')),
                ('height_field3', models.IntegerField(default=0)),
                ('width_field3', models.IntegerField(default=0)),
                ('imagen4', models.ImageField(blank=True, height_field='height_field4', upload_to='', width_field='width_field4')),
                ('height_field4', models.IntegerField(default=0)),
                ('width_field4', models.IntegerField(default=0)),
                ('contenido', models.TextField()),
                ('precio', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
