# Generated by Django 2.0.2 on 2018-05-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20180528_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='comprobacion',
            field=models.ImageField(blank=True, height_field='height_field2', null=True, upload_to='', width_field='width_field2'),
        ),
        migrations.AddField(
            model_name='factura',
            name='height_field2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='factura',
            name='width_field2',
            field=models.IntegerField(default=0),
        ),
    ]
